### ISSUE TITLE
Scriptify/document project bootstrapping

### ISSUE THREAD

**Issue by SethDavenport** [rangle/react-redux-starter#22]
Not really an issue.  However somewhere I'd like to script the steps I use to start up a project from a seed repo.  This script should also work for the angular one.  

Anyhow here's what I've been using:

```sh
git clone {seed-repo} --depth=0
rm -rf .git
git init
git remote add upstream {actual-project-repo}
git remote set-url origin {personal-fork-of-actual-project-repo}
```

I'd also like to see a howto in the `dev` repo along the lines of: "How to start a new repo"

Angular 1x Transitional: 

`bootstrap.sh angular-typescript-starter {project-name} {github-user-name}`
`clusternator init`

React:

`bootstrap.sh react-redux-seed {project-name} {github-user-name}`
`clusternator init`

**Comment by neilff** [comment]
:+1: this would be really nice

**Comment by andrewdamelio** [comment]
:+1:  agreed!

**Comment by SethDavenport** [comment]
See here: https://github.com/rangle/dev/pull/131

**Comment by neilff** [comment]
Closing as a result https://github.com/rangle/dev/pull/131
