### ISSUE TITLE
Change name to react-redux-starter

### ISSUE THREAD

**Issue by neilff** [rangle/react-redux-starter#23]
I think this has gone a bit beyond a seed (because of the included components, and multiple routes), and the angular sister project is titled `ng-typescript-webpack-starter`. 

Or at the least, both projects should have a similar title, differentiated only by angular / react.

Thoughts?

**Comment by andrewdamelio** [comment]
To clarify, your saying break out this out into two repo's?
- react-redux-seed
- react-redux-starter

**Comment by SethDavenport** [comment]
I agree the names should be the same.

I don't want to break them up for now.  I want a _simple_ workflow for spinning up a new project.

**Comment by neilff** [comment]
No breaking up, just aligning the name for the two repositories. I am leaning towards renaming to `react-redux-starter` because this is less of a seed, and more of a starter project now.

**Comment by SethDavenport** [comment]
Works for me

**Comment by SethDavenport** [comment]
Done.  Don't forget to update your remotes

`git remote set-url upstream git@github.com:You/react-redux-starter`
