### ISSUE TITLE
Babel 5 is no longer being maintained. Upgrade to Babel 6

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/react-redux-starter#36]

**Comment by xorgy** [comment]
Babel 6 has Babel 5 as a devDependency, are there incompatibilities?

**Comment by winkerVSbecks** [comment]
Not sure, just bootstrapped a project using this repo and saw that message.

**Comment by rbrander** [comment]
I've been burned by using Babel 6 when it first came out.  I suggest waiting until the next minor release is out.

**Comment by winkerVSbecks** [comment]
:+1:

**Comment by neilff** [comment]
Agreed. When I attempted to migrate to Babel 6, it ended up being a huge pain.

**Comment by SethDavenport** [comment]
Moved to master issues repo: https://github.com/rangle/rangle-starter/issues/9
