### ISSUE TITLE
React Hot Reload will soon be deprecated

### ISSUE THREAD

**Issue by neilff** [rangle/react-redux-starter#4]
RHR is going to be deprecated in favour of React Transform. 

This change is quite significant. 

I'd recommend looking at their boilerplate project and bringing the changes in from over there https://github.com/gaearon/react-transform-boilerplate

There are some great features that come along with the React Transform ecosystem, we should look into taking advantage of what it offers.

**Comment by SethDavenport** [comment]
Is react transform ready for production now?  We need to find a balance between a seed project that is useful now vs. gold-plating it with all the new hotness.

We can always adjust it later if necessary; but I don't want to hold things up if React Transform isn't ready yet.

**Comment by neilff** [comment]
There are issues hot reloading stateless components but I believe this would also be an issue with HMR as well. 

It doesn't need to be in there now (I actually think it's not even possible as I believe they do not have support for Babel 6 atm). 

However I believe we should move towards it once HMR is deprecated.

**Comment by SethDavenport** [comment]
That makes sense - the intention is for the support team to update the seed project in step with changes like this.  But it has to be in a state where it can be easily used at any time for starting new projects.

**Comment by neilff** [comment]
Sounds good :+1:

**Comment by SethDavenport** [comment]
Moved to master issues repo: https://github.com/rangle/rangle-starter/issues/10
